version: "3"

services:
  energy-app-pg:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=energy

volumes:
  postgresql_data:
